TEAM_NAME_MAP = {
    "法兰克福": "Ein Frankfurt",
    "云达不来梅": "Werder Bremen",
    "拜仁慕尼黑": "Bayern Munich",
    "奥格斯堡": "Augsburg",
    "门兴格拉德巴赫": "M'gladbach",
    "霍芬海姆": "Hoffenheim",
    "弗赖堡": "Freiburg",
    "RB莱比锡": "RB Leipzig",
    "勒沃库森": "Leverkusen",
    "斯图加特": "Stuttgart",
    "波鸿": "Bochum",
    "沃尔夫斯堡": "Wolfsburg",
    "海登海姆": "Heidenheim",
    "多特蒙德" : "Dortmund",
    "科隆": "FC Koln",
    "柏林联合": "Union Berlin",
    "美因茨": "Mainz",
    "达姆施塔特": "Darmstadt",
    "恩波利": "Empoli",
    "维罗纳": "Verona",
    "弗罗西诺内": "Frosinone",
    "那不勒斯": "Napoli",
    "热那亚": "Genoa",
    "佛罗伦萨": "Fiorentina",
    "国际米兰": "Inter",
    "蒙扎": "Monza",
    "罗马": "Roma",
    "萨勒尼塔纳": "Salernitana",
    "萨索洛": "Sassuolo",
    "亚特兰大": "Atalanta",
    "莱切": "Lecce",
    "拉齐奥": "Lazio",
    "乌迪内斯": "Udinese",
    "尤文图斯": "Juventus",
    "都灵": "Torino",
    "卡利亚里": "Cagliari",
    "博洛尼亚": "Bologna",
    "AC米兰": "Milan",
    "尼斯": "Nice",
    "里尔": "Lille",
    "马赛": "Marseille",
    "雷姆": "Reims",
    "巴黎圣日耳曼": "Paris SG",
    "洛里昂": "Lorient",
    "布雷斯特": "Brest",
    "朗斯": "Lens",
    "克莱蒙": "Clermont",
    "摩纳哥": "Monaco",
    "蒙彼利埃": "Montpellier",
    "勒阿弗尔": "Le Havre",
    "南特": "Nantes",
    "图卢兹": "Toulouse",
    "雷恩": "Rennes",
    "梅斯": "Metz",
    "斯特拉斯堡": "Strasbourg",
    "里昂": "Lyon",
    "阿尔梅里亚": "Almeria",
    "巴列卡诺": "Vallecano",
    "塞维利亚": "Sevilla",
    "瓦伦西亚": "Valencia",
    "皇家社会": "Sociedad",
    "吉罗纳": "Girona",
    "拉斯帕尔马斯": "Las Palmas",
    "马略卡": "Mallorca",
    "毕尔巴鄂竞技": "Ath Bilbao",
    "皇家马德里": "Real Madrid",
    "塞尔塔": "Celta",
    "奥萨苏纳": "Osasuna",
    "比利亚雷亚尔": "Villarreal",
    "皇家贝蒂斯": "Betis",
    "赫塔菲": "Getafe",
    "巴塞罗那":"Barcelona",
    "加的斯": "Cadiz",
    "阿拉维斯": "Alaves",
    "马德里竞技": "Ath Madrid",
    "格拉纳达": "Granada",
    "伯恩利": "Burnley",
    "诺丁汉森林": "Nott'm Forest",
    "伯恩茅斯": "Bournemouth",
    "西汉姆联": "West Ham",
    "布莱顿": "Brighton",
    "卢顿": "Luton",
    "埃弗顿": "Everton",
    "富勒姆": "Fulham",
    "谢菲尔德联": "Sheffield United",
    "水晶宫": "Crystal Palace",
    "纽卡斯尔联": "Newcastle",
    "阿斯顿维拉": "Aston Villa",
    "布伦特福德": "Brentford",
    "托特纳姆热刺": "Tottenham",
    "切尔西": "Chelsea",
    "利物浦": "Liverpool",
    "曼联": "Man United",
    "狼队": "Wolves",
    "阿森纳": "Arsenal",
    "曼城": "Man City",
}

LEAGUE_NAME_MAP = {
    "英超": "E0",
    "德甲": "D1",
    "西甲": "SP1",
    "法甲": "F1",
    "意甲": "I1",
}