TEAM_NAME_MAP1 = {
    "Ein Frankfurt": "D1",
    "Werder Bremen": "D1",
    "Bayern Munich": "D1",
    "Augsburg": "D1",
    "M'gladbach": "D1",
    "Hoffenheim": "D1",
    "Freiburg": "D1",
    "RB Leipzig": "D1",
    "Leverkusen": "D1",
    "Stuttgart": "D1",
    "Bochum": "D1",
    "Wolfsburg": "D1",
    "Heidenheim": "D1",
    "Dortmund": "D1",
    "FC Koln": "D1",
    "Union Berlin": "D1",
    "Mainz": "D1",
    "Darmstadt": "D1",
    "Empoli": "I1",
    "Verona": "I1",
    "Frosinone": "I1",
    "Napoli": "I1",
    "Genoa": "I1",
    "Fiorentina": "I1",
    "Inter": "I1",
    "Monza": "I1",
    "Roma": "I1",
    "Salernitana": "I1",
    "Sassuolo": "I1",
    "Atalanta": "I1",
    "Lecce": "I1",
    "Lazio": "I1",
    "Udinese": "I1",
    "Juventus": "I1",
    "Torino": "I1",
    "Cagliari": "I1",
    "Bologna": "I1",
    "Milan": "I1",
    "Nice": "F1",
    "Lille": "F1",
    "Marseille": "F1",
    "Reims": "F1",
    "Paris SG": "F1",
    "Lorient": "F1",
    "Brest": "F1",
    "Lens": "F1",
    "Clermont": "F1",
    "Monaco": "F1",
    "Montpellier": "F1",
    "Le Havre": "F1",
    "Nantes": "F1",
    "Toulouse": "F1",
    "Rennes": "F1",
    "Metz": "F1",
    "Strasbourg": "F1",
    "Lyon": "F1",
    "Almeria": "SP1",
    "Vallecano": "SP1",
    "Sevilla": "SP1",
    "Valencia": "SP1",
    "Sociedad": "SP1",
    "Girona": "SP1",
    "Las Palmas": "SP1",
    "Mallorca": "SP1",
    "Ath Bilbao": "SP1",
    "Real Madrid": "SP1",
    "Celta": "SP1",
    "Osasuna": "SP1",
    "Villarreal": "SP1",
    "Betis": "SP1",
    "Getafe": "SP1",
    "Barcelona": "SP1",
    "Cadiz": "SP1",
    "Alaves": "SP1",
    "Ath Madrid": "SP1",
    "Granada": "SP1",
    "Burnley": "E0",
    "Nott'm Forest": "E0",
    "Bournemouth": "E0",
    "West Ham": "E0",
    "Brighton": "E0",
    "Luton": "E0",
    "Everton": "E0",
    "Fulham": "E0",
    "Sheffield United": "E0",
    "Crystal Palace": "E0",
    "Newcastle": "E0",
    "Aston Villa": "E0",
    "Brentford": "E0",
    "Tottenham": "E0",
    "Chelsea": "E0",
    "Liverpool": "E0",
    "Man United": "E0",
    "Wolves": "E0",
    "Arsenal": "E0",
    "Man City": "E0",
}